### ISSUE TITLE
Add a build on push to branch

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#307]
Make -j build_serif build_ebook as we had was good… now we only know if we break CI when doing a PR.

**Comment by hendricius** [comment]
> Make -j build_serif build_ebook as we had was good… now we only know if we break CI when doing a PR.

Would it be OK to use the latest image for pushes? Else we'd need to build 1 image for each push too.

**Comment by hendricius** [comment]
@cedounet the pushes now always use the latest image - which is the one from the main branch. This way we save some polar bears and don't build a new docker image on every push. For pull requests we always build a new image (mostly from cache) and then publish it so that we can later on in theory revert back to that particular image and see if things broke with a particular PR.

**Comment by cedounet** [comment]
I meant build the book.

no actions are triggered when I push to a branch.. it should try to build the book so you know early you broke something.

**Comment by cedounet** [comment]
I re-open as i just pushed something to https://github.com/hendricius/the-sourdough-framework/tree/313-kobo-flowcharts and no actions is to be seen.

**Comment by hendricius** [comment]
Could you try to reintegrate and see if it fixes it?

**Comment by cedounet** [comment]
I had not ran git fetch before the merge... _mea culpa_
